# Generated by Django 5.0.5 on 2024-10-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_section_syllabus_syllabus_testquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
