# Generated by Django 5.0.5 on 2024-10-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
